FORMAT: 1A
HOST: https://api.mis.tot.co.th/mis

# Introduction

  MIS API

  เอกสารการสเปค **MIS API.**
  ชื่อ และ type ตัวแปรที่ใช้ จะล้อตามโครงสร้างที่เกษตรกำหนดมา

  <img src="data\image\api_gateway.svg" width="100%">

  ภาพจำลองการเชื่อมต่อจากระบบอื่น การเชื่อมต่อจะเชื่อมต่อผ่าน **api gateway** ซึ่งจะทำหน้าที่ตรวจสอบสิทธิ์การใช้งานระบบ

# Group Authorization

  การใช้งาน จำเป็นต้องมี api key

# Group ปฏิบัติการ

## เพิ่มปฏิบัติการใหม่ \(ทดสอบตัวสร้างเอกสารยังไม่ใช่โครงสร้างข้อมูลจริง\) [POST /dispatch]

  **\(ทดสอบตัวสร้างเอกสารยังไม่ใช่โครงสร้างข้อมูลจริง\)**

  <img src="data\image\create_dispatch.svg">

  เปิดปฏิบัติการ 1 คน ต่อ 1 ห้อง MIS

+ Request (application/json)

    + Headers

            Authorization: Token {token}

    + Attributes (Dispatch , fixed-type)

+ Response 201 (application/json)

    + Attributes (object , fixed-type)
      + misRoomId: `22315` (string) - รหัสห้อง MIS
      + return (Dispatch)

## อัพเดทปฏิบัติการ [PUT /dispatch]

  <img src="data\image\update_dispatch.svg">

  **Message Queue**

  ในกรณี OIS ต้องการอัพเดทข้อมูลปฏิบัติการ ในระหว่างกำลังปฏิบัติงาน จะทำงานผ่าน Message Queue

+ Request (application/json)

    + Attributes (object , fixed-type)
      + event: `update_dispatch` (string, required) - กำหนดค่าคงที่
      + EventID: `610001` (number, required) - รหัสเหตุการณ์
      + OperationID: `610003` (number, required) - เลขปฏิบัติการ
      + dispatch (Dispatch) - ข้อมูลปฏิบัติการ


## ผู้ป่วย ขึ้น/เปลี่ยน พาหนะ [PUT /dispatch/vehicle]

  ในกรณีที่มีพาหนะ หลายอย่างออกไปรับผู้ป่วย 1 คน เช่น มีการใช้รถรวมกันระว่าง FR กับ ALS ประสานงานกันรับผู้ป่วย

## ส่งรายงานปฏิบัติงาน [POST /dispatch]

## แก้ไขรายงานปฏิบัติงาน [PUT /dispatch/{idxxx}]

  หลังจากส่งรายงานการปฏิบัติงานแล้วอนุญาติให้แก้ไขได้ภายใน 24 ชม. หลังปิดเคส

## UI สำหรับแสดงผล MIS [GET /dispatch/{misRoomId}]

  หน้าจอส่วนแสดงผลที่จะนำไปใส่ในระบบอื่น

# Group จัดการเวร

## เข้าเวร/ออกเวร [PUT /duty]

# Group Protocol

## Offline protocol [GET /protocol]

## Online protocol [GET /protocol]

# Group Lookup

## Special list [GET /specialist{?province,query}]

+ Parameters
    + province: `สระแก้ว` (string)
      ``ชื่อจังหวัด``
    + query: `กระดูก` (string)
      ``ข้อมูล query อื่นๆ เช่น กระดูก, หัวใจ, สมอง``

## สิทธิ์/ประวัดิการรักษา [GET /rightoftreatment/{id_card}]

  สิทธิ์/ประวัดิการรักษา รวมถึงข้อมูลส่วนบุคคลอื่นๆ ด้วย

**(รอหารือกับทีมอีกครั้งว่าสมควรดึงได้โดยตรงไหม เพราะเป็นข้อมูลละเอียดอ่อน)**

+ Parameters
    + id_card: `3250400000001` (string, required)
      ``หมายเลขประจำตัวประชาชน``

## สมาชิกในทีมปฏิบัติการ [GET /operating/{OperatingSetID}]

  + Parameters
      + OperatingSetID: `23154` (number, required)
        ``ชุดปฏิบัติการ (ทะเบียนชุดปฏิบัติการ)``

# Group ระบบ Telemed

## ข้อมูลสัญญาณชีพ html [GET /telemed/vitalsigns/{PersonID}]

+ Parameters
    + PersonID: `002321` (number, required)
      ``รหัสข้อมูลบุคคล``

## ข้อมูลสัญญาณชีพ json [GET /telemed/vitalsigns/{PersonID}]

+ Parameters
    + PersonID: `002321` (number, required)
      ``รหัสข้อมูลบุคคล``

# Group Notification

## ส่ง Notification ไประบบอื่น [PUT /notification]

  **Message Queue**

  <img src="data\image\notification_system_002.svg">

  <img src="data\image\notification_system_003.svg">

  ในที่นี้สำหรับใช้ในกรณี mis ต้องการส่ง Notification ไปยังศูนย์สั่งการ

## รับ Notification จากระบบอื่น [POST /notification]

  **Message Queue**

  <img src="data\image\notification_system.svg">

  <img src="data\image\notification_system_001.svg">

  ใช้ในกรณีระบบอื่นต้องการส่ง Notification ไปยังผู้ใช้ MIS ในที่นี้จะใช้สำหรับ ศูนย์สั่งการต้องการเรียกหมอ

## รับ Alert จากระบบอื่น [POST /notification]

  **Message Queue**

  ใช้ในกรณีระบบอื่น ต้องการส่ง Alert message ไปยังผู้ใช้ MIS

  (รอหารือกับทีมอีกครั้ง ว่าจะทำตรงนี้หรือไม่)

## Data Structures

# Dispatch (object)
+ type: `Dispatch` (string, fixed, required) - ค่าคงที่
+ EventID: `610001` (number, required) - รหัสเหตุการณ์
+ OperationID: `610003` (number, required) - เลขปฏิบัติการ
+ VehicleIID: `6กจ9999`, `9ดม2448` (array[string]) - เลขรถปฏิบัติการ (ทะเบียนยานพาหนะ)
+ OfficeID: `1111` (number, required) - หน่วยปฏิบัติการ (ทะเบียนหน่วยงาน)
+ OperatingSetID: `23154`,`22314` (array[number]) - ชุดปฏิบัติการ (ทะเบียนชุดปฏิบัติการ)
+ O_Victim (Victim) - ข้อมูลผู้ป่วย

# Victim (object)
+ type: `Victim` (string, required)
+ EventPatientID: `2222` (number) - รหัสรายละเอียดผู้ประสบเหตุ
+ EventID: `610001` (number) - รหัสเหตุการณ์
+ CBDCode: `CBD25` (string) - อาการผู้ป่วยที่แจ้ง
+ PatientName: `002321` (number) - ชื่อผู้ป่วย ชุดข้อมูลบุคคล PersonID
+ CitizenID: `3250400000001` (string) - หมายเลขประจำตัวประชาชน
+ EmergencyLevelCode: `02` (string) - ระดับความรุนแรง 01=ขาว, 02=เขียว, 03=เหลือง, 04=แดง, 05=ดำ

# Person (object)
+ PersonID: `002321` (number) - รหัสข้อมูลบุคคล
+ CitizenID: `3250400000001` (string) - หมายเลขประจำตัวประชาชน
+ PrefixCode: `001` (string) - คำนำหน้าชื่อ ไฟล์ prefix.xlsx
+ GivenName: `แสม` (string) - ชื่อตัว
+ FamilyName: `แสนซน` (string) - ชื่อสกุล
+ GenderCode: `1` (number) - เพศ 1=ชาย (male), 2=หญิง (Female), 9=ไม่สามารถระบุได้ (not applicable)
+ BirthDate: `1990-01-25` (string) - วันเกิด
+ BirthJurisdiction: `ลพบุรี` (string) - สถานที่เกิด จังหวัด
+ NationalityCode: `TH` (string) - สัญชาติ File Nationality.xlsx
+ LifeStatusCode: `LI` (string) - สถานะการมีชีวิต EN=เสียชีวิต, LI=มีชีวิต
+ DisabilityCode: `00` (string) - ความพิการ File Disability.xlsx

# Vehicle (object)
+ type: `Vehicle` (string, required) - ค่าคงที่
+ Vehicle_Id: `10-1-VEH-10010200034` (string) - รหัสชุดปฏิบัติการ
+ Vehicle_Name: `โรงพยาบาลวิภาวดี 3กษ 8019` (string) - ชื่อชุดปฏิบัติการ

# Vehicle_Level (enum)
+ ALS - ปฏิบัติการฉุกเฉินระดับสูง
+ ILS - ปฏิบัติการฉุกเฉินระดับกลาง
+ BLS - ปฏิบัติการฉุกเฉินระดับต้น
+ FR - ปฏิบัติการฉุกเฉินเบื้องต้น

# Medical (object)
+ type: `Medical` (string, fixed) - ค่าคงที่
+ Name - ชื่อ
+ No - เลขที่ใบประกอบ
+ Tel - เบอร์โทรศัพท์
