FORMAT: 1A
HOST: https://api.mis.tot.co.th/mis

MIS API

เอกสารการสเปค **MIS API.**
ชื่อ และ type ตัวแปรที่ใช้ จะล้อตามระบบ api ของระบบ ITEM สพฉ.

# ปฏิบัติการ [/dispatch]

## เพิ่มปฏิบัติการใหม่ (ทดสอบตัวสร้างเอกสารยังไม่ใช่โครงสร้างข้อมูลจริง) [POST /dispatch]

<img src="data\image\create_dispatch.svg">
เปิดปฏิบัติการ 1 คน ต่อ 1 ห้อง MIS

+ Request (application/json)

    + Headers

            Authorization: Bearer {token}

    + Attributes (Dispatch , fixed-type)

+ Response 201 (application/json)

    + Attributes (Dispatch , fixed-type)

## อัพเดทปฏิบัติการ [/dispatch]

  <img src="data\image\update_dispatch.svg">

  ในกรณี OIS ต้องการอัพเดทข้อมูลปฏิบัติการ ในระหว่างกำลังปฏิบัติงาน

## เมื่อผู้ป่วยขึ้นรถ หรือ มีการเปลี่ยนพาหนะ [/dispatch]

  ในกรณีที่มีพาหนะ หลายอย่างออกไปรับผู้ป่วย 1 คน เช่น มีการใช้รถรวมกันระว่าง FR กับ ALS ประสานงานกันรับผู้ป่วย

## ส่งรายงานปฏิบัติงาน [POST /dispatch]

## แก้ไขรายงานปฏิบัติงาน 24 ชม. [PUT /dispatch/{idxxx}]

# จัดการเวร [/duty]

## เข้าเวร/ออกเวร [PUT /duty]

# Protocol [/protocol]

## Offline protocol [GET /protocol]

## Online protocol [GET /protocol]

# Lookup [/lookup]

## ดึงข้อมูล Special list จาก OIS [GET /specialist]

## ดึงข้อมูลสิทธิ์/ประวัดิการรักษา [GET /rightoftreatment/{id card}]

# ระบบ Telemed [/telemed]

## ข้อมูลสัญญาณชีพ html [GET /telemed/vitalsigns]

## ข้อมูลสัญญาณชีพ json [GET /telemed/vitalsigns]

# Notification [/notification]

## Data Structures

# Dispatch (object)
+ type: `Dispatch` (string, fixed, required) - ค่าคงที่
+ EventID: `610001` (number, required) - รหัสเหตุการณ์ ss
+ OperationID: `610003` (number, required) - เลขปฏิบัติการ ss
+ VehicleIID: : `6กจ9999`, `9ดม2448` (array[string]) - เลขรถปฏิบัติการ (ทะเบียนยานพาหนะ)
+ OfficeID (number, required) - หน่วยปฏิบัติการ (ทะเบียนหน่วยงาน)
+ OperatingSetID: `23154`,`22314` (array[number]) - ชุดปฏิบัติการ (ทะเบียนชุดปฏิบัติการ)
+ O_Victim (Victim) - ข้อมูลผู้ป่วย

# Victim (object)
+ EventPatientID (number) - รหัสรายละเอียดผู้ประสบเหตุ
+ EventID: `610001` (number) - รหัสเหตุการณ์
+ CBDCode: `CBD25` (string) - อาการผู้ป่วยที่แจ้ง
+ PatientName: `002321` (number) - ชื่อผู้ป่วย ชุดข้อมูลบุคคล PersonID
+ CitizenID: `3250400000001` (string) - หมายเลขประจำตัวประชาชน
+ EmergencyLevelCode: `02` (string) - ระดับความรุนแรง 01=ขาว, 02=เขียว, 03=เหลือง, 04=แดง, 05=ดำ

# Person (object)
+ PersonID: `002321` (number) - รหัสข้อมูลบุคคล
+ CitizenID: `3250400000001` (string) - หมายเลขประจำตัวประชาชน
+ PrefixCode: `001` (string) - คำนำหน้าชื่อ ไฟล์ prefix.xlsx
+ GivenName: `แสม` (string) - ชื่อตัว
+ FamilyName: `แสนซน` (string) - ชื่อสกุล
+ GenderCode: `1` (number) - เพศ 1=ชาย (male), 2=หญิง (Female), 9=ไม่สามารถระบุได้ (not applicable)
+ BirthDate: `1990-01-25` (string) - วันเกิด
+ BirthJurisdiction: `ลพบุรี` (string) - สถานที่เกิด จังหวัด
+ NationalityCode: `TH` (string) - สัญชาติ File Nationality.xlsx
+ LifeStatusCode: `LI` (string) - สถานะการมีชีวิต EN=เสียชีวิต, LI=มีชีวิต
+ DisabilityCode: `00` (string) - ความพิการ File Disability.xlsx

# Vehicle (object)
+ type: `Vehicle` (string, fixed) - ค่าคงที่
+ Vehicle_Id: `10-1-VEH-10010200034` (string) - รหัสชุดปฏิบัติการ
+ Vehicle_Name: `โรงพยาบาลวิภาวดี 3กษ 8019` (string) - ชื่อชุดปฏิบัติการ

# Vehicle_Level (enum)
+ ALS - ปฏิบัติการฉุกเฉินระดับสูง
+ ILS - ปฏิบัติการฉุกเฉินระดับกลาง
+ BLS - ปฏิบัติการฉุกเฉินระดับต้น
+ FR - ปฏิบัติการฉุกเฉินเบื้องต้น

# Medical (object)
+ type: `Medical` (string, fixed) - ค่าคงที่
+ Name - ชื่อ
+ No - เลขที่ใบประกอบ
+ Tel - เบอร์โทรศัพท์
