@startuml
  :OIS Platform : as OIS
  :MIS system : as MIS
  : MIS api gateway : as (gateway)

  gateway <-- OIS : call api
  MIS <-- gateway

  : Outbound Queue : as (outbound)
  MIS ----> outbound : notification to OIS

  outbound --> OIS

  : Inbound Queue : as (inbound)
  OIS ----> inbound : notification to MIS
  inbound -> MIS

  MIS --> OIS : call api

@enduml
