@startuml
  "OIS Platform"  as [OIS]
  : MIS api gateway : as (gateway)

  package "MIS Platform" as MIS{
    [MIS Room]
    [Telemed]
    [Vital Sign]
    [Conference]
    [Protocol]
    [Victim]
    [MIS User] as User
    [Vehicle\nCamera] as Vehicle

    [MIS Room] -- [Telemed]
    [MIS Room] -- [Conference]
    [MIS Room] -- [Protocol]
    [MIS Room] -- [Victim]
    [MIS Room] -- User

    [Telemed] - [Vital Sign]
    [Telemed] -- Vehicle

  }

  gateway <-- OIS : call api
  MIS <-- gateway

  : Outbound Queue : as (outbound)
  MIS ----> outbound : notification to OIS

  outbound --> OIS

  : Inbound Queue : as (inbound)
  OIS ----> inbound : notification to MIS
  inbound -> MIS

  MIS --> OIS : call api

@enduml
