@startuml
Title Use case

  usecase (MIS\nLogin) as MISLogin

  rectangle {
    usecase (Grant\nPermission) as GrantPermission
    usecase (Recive\nGrant) as ReciveGrant
    GrantPermission ..> ReciveGrant:<extend>
  }
  rectangle {
    usecase (Meeting\nRoom) as MeetingRoom
    usecase (Close\nRoom) as CloseRoom
    usecase (Invite\nto Meeting Room) as InviteToMeetingRoom
    usecase (Recive\nInvite) as ReciveInvite
    MeetingRoom -- CloseRoom
    InviteToMeetingRoom ..> ReciveInvite :<extend>
  }

  rectangle {
    :Supervisor: as Supervisor
    :Coordinator: as Coordinator
    :Dispatcher: as Dispatcher
    :CallTaker: as CallTaker
    Supervisor ..> Coordinator :<extend>
    Supervisor ..> Dispatcher :<extend>
  }

  rectangle {
    :Specialist: as Specialist
    :ER: as ER
    Specialist ..> ER :<extend>
  }

  rectangle {
    usecase (Protocol) as Protocol
    usecase (Offline Note) as Offline
    usecase (Online Note) as Online
    usecase (Operation Note) as Ops
    usecase (Medicine Note) as Med
    usecase (Check List) as Check
    Protocol ..> Offline
    Protocol ..> Online
    Online ..> Ops
    Online ..> Med
    Med ..> Check
  }


  rectangle {
    usecase (Telemed) as Telemed
    usecase (Live\nVideo) as LiveVideo
    usecase (Vital Sign) as VitalSign
    usecase (Switch Partient\nVital Sign) as SwitchVS
    Telemed -- LiveVideo
    Telemed -- VitalSign
    VitalSign -- SwitchVS
  }

  package OIS{
    usecase (Update Patiant\nStatus) as UpdatePatiantStatus
    usecase (ER/Specialist\nInfomation) as ERSpecialistInfomation
    usecase (check in/out) as checkIn
    usecase (Assign\nAmbulance) as AssignAmbulance
    usecase (Switch\nAmbulance) as SwitchAmbulance
    AssignAmbulance ..> SwitchAmbulance
  }

  CallTaker --> UpdatePatiantStatus
  CallTaker --> AssignAmbulance

  Coordinator --> ERSpecialistInfomation
  Coordinator --> MeetingRoom: Case G, Y
  Coordinator ----> Protocol
  Coordinator ----> CloseRoom

  Dispatcher ---------> ERSpecialistInfomation
  Dispatcher ---------> MeetingRoom : Case R
  Dispatcher ------> InviteToMeetingRoom
  Dispatcher ------> Protocol
  Dispatcher ------> CloseRoom

  ER --> ReciveInvite
  ER --> MISLogin

  Specialist ------> MeetingRoom
  Specialist --> ReciveGrant
  Specialist ------> ReciveInvite

  Paramedic ------> MISLogin
  Paramedic ------> MeetingRoom
  Paramedic ------> Protocol
  Paramedic ------> SwitchVS
  Paramedic ------> Med
  Paramedic ------> Check
  Paramedic ------> checkIn
  Paramedic ------> SwitchAmbulance
  Paramedic ------> UpdatePatiantStatus

  :Medical Director: as MD
  MD ------> MISLogin
  MD -----> MeetingRoom
  MD ---> GrantPermission
  MD ----> InviteToMeetingRoom
  MD ----> ReciveInvite
  MD ------> checkIn
  MD ----> ERSpecialistInfomation
  MD -up-> Protocol

@enduml
