@startuml
Title Use case
  usecase (Meeting\nRoom) as MeetingRoom
  usecase (Close\nRoom) as CloseRoom
  usecase (Protocol) as Protocol
  usecase (Operation) as Ops
  usecase (MIS\nLogin) as MISLogin
  usecase (Medicine) as Med
  usecase (Check) as Check
  usecase (Invite\nto Meeting Room) as InviteToMeetingRoom
  usecase (Recive\nInvite) as ReciveInvite
  usecase (Grant\nPermission) as GrantPermission
  usecase (Recive\nGrant) as ReciveGrant
  usecase (Telemed) as Telemed
  usecase (Live\nVideo) as LiveVideo
  usecase (Vital Sign) as VitalSign
  usecase (Switch Partient\nVital Sign) as SwitchVS

  package OIS{
    usecase (Update Patiant\nStatus) as UpdatePatiantStatus
    usecase (ER/Specialist\nInfomation) as ERSpecialistInfomation
    usecase (check in/out) as checkIn
    usecase (Assign\nAmbulance) as AssignAmbulance
    usecase (Switch\nAmbulance) as SwitchAmbulance
    AssignAmbulance ....> SwitchAmbulance
  }

  MeetingRoom ------ CloseRoom
  Protocol ....> Ops
  Protocol ....> Med
  Med ....> Check
  InviteToMeetingRoom ....> ReciveInvite :<extend>
  GrantPermission ....> ReciveGrant:<extend>
  Telemed -- LiveVideo
  Telemed -- VitalSign
  VitalSign -- SwitchVS


  Supervisor ..> Coordinator :<extend>
  Supervisor ..> Dispatcher :<extend>

  CallTaker ---> UpdatePatiantStatus
  CallTaker ---> AssignAmbulance

  Coordinator ------> ERSpecialistInfomation
  Coordinator ------> MeetingRoom: Case G, Y
  Coordinator --> checkIn
  Coordinator ------> Protocol
  Coordinator ------> CloseRoom

  Dispatcher ------> ERSpecialistInfomation
  Dispatcher ------> MeetingRoom : Case R
  Dispatcher --> checkIn
  Dispatcher ------> InviteToMeetingRoom
  Dispatcher ------> Protocol
  Dispatcher ------> CloseRoom

  ER ------> ReciveInvite
  ER ------> MISLogin

  Specialist ....> ER :<extend>
  Specialist ------> MeetingRoom
  Specialist ------> ReciveGrant
  Specialist ------> ReciveInvite

  Paramedic ------> MISLogin
  Paramedic ------> MeetingRoom
  Paramedic ------> Protocol
  Paramedic ------> SwitchVS
  Paramedic ------> Med
  Paramedic ------> Check
  Paramedic ------> checkIn
  Paramedic ------> SwitchAmbulance
  Paramedic ------> UpdatePatiantStatus

  :Medical Director: as MD
  MD ------> MISLogin
  MD ------> MeetingRoom
  MD ------> GrantPermission
  MD ------> InviteToMeetingRoom
  MD ------> ReciveInvite
  MD ------> checkIn
  MD ------> ERSpecialistInfomation

@enduml
