@startuml
Title การสร้างห้อง __MIS__
  actor "OIS ผู้ปฏิบัติงาน" as OIS
  OIS -> "OIS api": กดรับงาน
  "OIS api"-> "MIS api": POST /ROOM\nส่งคำสั่งเปิดห้อง MIS
  "MIS api" -> "MIS api": สร้างห้อง MIS

  "MIS api" -> "Media api": Create vdo conference
  "MIS api" <-- "Media api": Session ห้อง vdo conference

  "OIS api"<-- "MIS api": Reponse 201\nหมายเลขห้อง MIS
  OIS <-- "OIS api": Link เข้าห้อง

  "MIS api" -> "Vehicle api": Query telemed link with car_id
  "MIS api" <-- "Vehicle api": Camera link key, Virtual sign link key

  "MIS api" -> "Call alert": เรียกเข้าห้อง แพทย์, ER

  actor "MIS App\nEmergency physician" as MD
  actor "MIS App\nEmergencyRoom" as ER

  "Call alert" --> MD: Call alert mis room
  "Call alert" --> ER: Call alert mis room

  "MIS api" -> "Panel PC api": \nRegister\nkey:{vehicleId=slcus050_id=slcus020_id}\npriority:1\nstatusRoom:เปิดห้อง
  note left: priority\nถ้าเป็น 1 เรียกเข้าห้องอัตโนมัติ
@enduml
