@startuml
Title การสร้างห้อง __MIS__
  actor "OIS ผู้ปฏิบัติงาน" as OIS
  OIS -> "OIS api": กดรับงาน
  "OIS api"-> "MIS api": POST /ROOM\nส่งคำสั่งเปิดห้อง MIS

  database "MIS\nDatabase" as misdb
  group check รหัสประเมิน
    "MIS api" -> misdb: Query with slcus050_id
    hnote over "MIS api"
      check รหัสประเมินต้องไม่ซ้ำกัน
    endnote
  end
  "MIS api" -> "MIS api": สร้างห้อง MIS\nRandom Media api link

  collections "Media api" as MediaApi
  "MIS api" -> MediaApi: Create vdo conference
  "MIS api" <-- MediaApi: Session ห้อง vdo conference
  "MIS api" -> misdb: save

  "OIS api"<-- "MIS api": Reponse 201 Return MIS room object.\nหมายเลขห้อง MIS
  OIS <-- "OIS api": Link เข้าห้อง

  "MIS api" -> "Vehicle api": Query telemed link with vehicleId
  "MIS api" <-- "Vehicle api": Camera link key, Virtual sign link key
  "MIS api" -> misdb: ถ้ามีข้อมูล Telemed link key -> save
  "MIS api" -> "Call alert": เรียกเข้าห้อง แพทย์, ER

  actor "MIS User\nEmergency physician" as MD
  actor "MIS User\nEmergencyRoom" as ER

  "Call alert" -> MD: Call alert mis room
  "Call alert" -> ER: Call alert mis room

  "MIS api" -> "Panel PC api": \nRegister\nkey:{vehicleId=slcus050_id=slcus020_id}\nautojoin:true\nactive:true
  note left: autojoin\nถ้าเป็น true เรียกเข้าห้องอัตโนมัติ
  database "Panel PC\nDatabase" as paneldb
  "Panel PC api" -> paneldb: save
  note left
    Body
    {
      vehicleId
      slcus050_id
      slcus020_id
      active
      autojoin
    }
  endnote
@enduml
