@startuml
Title การอัพเดทข้อมูลห้อง __MIS__
  actor "OIS\nเจ้าหน้าที่" as OIS
  OIS -> "OIS api": มีการปรับสถานะห้อง MIS

  "OIS api"-> "MIS api": PUT /Room/{misRoomId} with MIS room object.\nส่งข้อมูล update ห้อง MIS
  rnote over "OIS api"
    มีการที่สามารถอัพเดทได้
    - รายการพาหนะ ที่เข้าร่วม
    - รายการเจ้าหน้าที่ ที่เข้าร่วม
    - รพ. ปลายทาง
  endnote
  database "MIS\nDatabase" as misdb
  "MIS api" -> misdb: Query with misRoomId
  "MIS api" <-- misdb: MIS room object.

  hnote over "MIS api"
    ตรวจสอบ สถานะพาหนะ
    มีการถอดพาหนะหรือไม่
    มีการเพิ่มพาหนะหรือไม่
  endnote

  "MIS api" -> misdb: save
  note left
    update MIS room object
  endnote

  "OIS api" <-- "MIS api": 200 OK Return body mis room object.
  rnote over "MIS api"
    - ถอดกล้องทั้งหมด
      แล้วเสียบกล้องอันล่างสุดใน
      รายการ vehicleId เข้าไปแทน
    - เปลี่ยน link ไวทัลไซ
  endnote
  "MIS api" -> "Panel PC api": \nUpdate ข้อมูลรายการพาหนะ\nkey:{vehicleId=slcus050_id=slcus020_id}\nBody ...\nautojoin:true\nactive:**false/true**

  note left
    - หากมีการเพิ่มพาหนะใหม่ active:true
      หากภาหนะไหนหายไปจากรายการ vehicleId ให้กำหนด **active:false**
    - เมื่อเพิ่มพาหนะถ้ากำหนด **autojoin:true** ให้ขึ้นเตือนเข้าห้อง
      Body
      {
        vehicleId รหัสพาหนะ
        operatorID คนที่กดรับงาน
        misRoomId
        slcus050_id
        slcus020_id
        autojoin
        active
      }
  endnote
  database "Panel PC\nDatabase" as paneldb
  "Panel PC api" -> paneldb: save

  queue "Panel PC\nQueue" as panelq
  "Panel PC api" -> panelq: Send body to topic vehicleId

@enduml
