@startuml
Header notification_system
  :Other Platform : as Other
  :MIS User : as MIS
  Other -right-> MIS : ต้องการส่ง Notification
@enduml

@startuml
Header notification_system_001
  actor "Other Platform" as Other
  collections "Inbound Queue" as inbound
  Other --> inbound : Notification message
  actor "Mis User" as MIS
  inbound --> MIS : Notification message
@enduml

@startuml
Header notification_system_002
  :Other Platform : as Other
  :MIS User : as MIS
  MIS -right-> Other : ต้องการส่ง Notification
@enduml

@startuml
Header notification_system_003
  actor "Mis User" as MIS
  collections "Outbound Queue" as outbound
  MIS --> outbound : Notification message
  actor "Other Platform" as Other
  outbound --> Other : Notification message
@enduml
