@startuml
Header notification_system
  :OIS Platform : as OIS
  :MIS User : as MIS
  OIS -right-> MIS : ต้องการส่ง Notification
@enduml

@startuml
Header notification_system_001
  actor "OIS Platform" as OIS
  collections "Inbound Message Queue" as inbound
  OIS --> inbound : Notification message
  actor "Mis User" as MIS
  inbound --> MIS : Notification message
@enduml

@startuml
Header notification_system_002
  :OIS Platform : as OIS
  :MIS User : as MIS
  MIS -right-> OIS : ต้องการส่ง Notification
@enduml

@startuml
Header notification_system_003
  actor "Mis User" as MIS
  collections "Outbound Message Queue" as outbound
  MIS --> outbound : Notification message
  actor "OIS Platform" as OIS
  outbound --> OIS : Notification message
@enduml
