@startuml
Header ois_get_room_in_event
  actor "OIS Platform" as OIS

  OIS --> "MIS Platform" : ขอรายการห้อง MIS ที่กำลังปฏิบัติงาน\nภายใต้เลขเหตุการณ์เดียวกัน
  "MIS Platform" --> OIS : รายการห้อง MIS
@enduml
