@startuml
Title __Paramedic__
  :Paramedic: as Paramedic

  usecase (Protocol) as Protocol
  usecase (Offline Note) as Offline
  usecase (Online Note) as Online
  usecase (Operation Note) as Ops
  usecase (Medicine Note) as Med
  usecase (Check List) as Check
  Protocol ..> Offline : ทำบันทึก
  Protocol ..> Online : รับคำสั่ง\nทำบันทึก
  note top of Online : ทำรายงาน\nที่รับคำสั่งมา\nหรือบันทึกเพิ่มได้
  Online ..> Ops
  Online ..> Med
  Med ..> Check

  usecase (MIS\nLogin) as MISLogin
  usecase (Meeting\nRoom) as MeetingRoom

  usecase (Switch Patient\nVital Sign) as SwitchVS
  usecase (Switch\nAmbulance) as SwitchAmbulance
  usecase (Update Patiant\nStatus) as UpdatePatiantStatus

  Paramedic -left-> MISLogin
  Paramedic --> MeetingRoom
  Paramedic --> SwitchVS
  Paramedic --> SwitchAmbulance: รับคำสั่งจาก\nOIS
  Paramedic --> UpdatePatiantStatus
  Paramedic ---> Protocol

@enduml
