@startuml
Title __Specialist__

  rectangle {
    :Specialist: as Specialist
  }

  rectangle {
    usecase (Meeting\nRoom) as MeetingRoom
    usecase (Invite\nto Meeting Room) as InviteToMeetingRoom
    usecase (Recive\nInvite) as ReciveInvite
    InviteToMeetingRoom ..> ReciveInvite :<extend>
  }

  rectangle {
    usecase (Grant\nPermission) as GrantPermission
    usecase (Recive\nGrant) as ReciveGrant
    GrantPermission ..> ReciveGrant:<extend>
  }

  Specialist ----> ReciveGrant : รับหน้าที่จาก\nMedical Director
  Specialist --> MeetingRoom
  Specialist --> ReciveInvite

@enduml
