@startuml
Title __Dispatcher__
  :Dispatcher: as Dispatcher

  usecase (Protocol) as Protocol
  usecase (Offline Note) as Offline
  usecase (Online Note) as Online
  usecase (Operation Note) as Ops
  usecase (Medicine Note) as Med
  Protocol ..> Offline
  Protocol ..> Online
  Online ..> Ops
  Online ..> Med

  usecase (Meeting\nRoom) as MeetingRoom
  usecase (Close\nRoom) as CloseRoom
  usecase (Invite\nMedical Director) as InviteMD

  Dispatcher --> MeetingRoom
  Dispatcher --> CloseRoom
  Dispatcher --> Protocol : ดูได้\nทำบันทึกได้
  Dispatcher --> InviteMD : เรียก\nMedical Director

@enduml
