@startuml
Title __Coordinator__
  :Coordinator: as Coordinator

  usecase (Protocol) as Protocol
  usecase (Offline Note) as Offline
  usecase (Online Note) as Online
  usecase (Operation Note) as Ops
  usecase (Medicine Note) as Med
  Protocol ..> Offline
  Protocol ..> Online
  Online ..> Ops
  Online ..> Med

  usecase (Meeting\nRoom) as MeetingRoom
  usecase (Close\nRoom) as CloseRoom
  usecase (Invite\nMedical Director) as InviteMD

  Coordinator --> MeetingRoom
  Coordinator --> CloseRoom
  Coordinator --> Protocol : ดูได้\nทำบันทึกได้
  Coordinator --> InviteMD : เรียก\nMedical Director

@enduml
