@startuml
Title __Coordinator__
  :Coordinator: as Coordinator

  usecase (Protocol) as Protocol
  usecase (Offline Note) as Offline
  usecase (Online Note) as Online
  usecase (Operation Note) as Ops
  Protocol ..> Offline
  Protocol ..> Online
  Online ..> Ops

  usecase (MIS\nLogin) as MISLogin
  usecase (Meeting\nRoom) as MeetingRoom
  usecase (Close\nRoom) as CloseRoom
  usecase (Invite\nto Meeting Room) as InviteToMeetingRoom

  Coordinator -left-> MISLogin
  Coordinator --> MeetingRoom
  Coordinator --> CloseRoom
  Coordinator --> Protocol : ดูได้

@enduml
