@startuml
Title __Medical Director__
  :Medical Director: as MD

  usecase (Protocol) as Protocol
  usecase (Offline Note) as Offline
  usecase (Online Note) as Online
  usecase (Operation Note) as Ops
  usecase (Medicine Note) as Med
  Protocol ..> Offline
  Protocol ..> Online
  Online ..> Ops
  Online ..> Med

  usecase (check\nin/out) as checkIn
  usecase (MIS\nLogin) as MISLogin
  usecase (ER/Specialist\nInfomation) as ERSpecialistInfomation

  usecase (Meeting\nRoom) as MeetingRoom
  usecase (Invite\nto Meeting Room) as InviteToMeetingRoom
  usecase (Recive\nInvite) as ReciveInvite
  InviteToMeetingRoom ..> ReciveInvite :<extend>

  usecase (Grant\nPermission) as GrantPermission

  MD -right-> checkIn : เข้าเวร\nออกเวร
  MD -left-> MISLogin
  MD --> MeetingRoom
  MD --> ERSpecialistInfomation
  MD --> Protocol : สั่งการได้
  MD --> InviteToMeetingRoom
  note top of InviteToMeetingRoom : เรียกหมอท่านอื่นได้

  MD --> ReciveInvite
  MD --> GrantPermission : โยกสิทธิ์การอำนวยการ

@enduml
