@startuml
Title Update Dispatch
actor "OIS Platform" as OIS
  OIS -> "MIS Platform": ส่งข้อมูล Update
  note left: เกิดเหตุเกิดเหตุบางอย่าง\nที่จำเป็นต้องมีการ Update ภารกิจ\nที่กำลังดำเนินอยู่
  "MIS Platform" -> "MIS Platform": update MIS
  "MIS Platform" -> OIS: 200 OK
@enduml
