name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8]

    steps:
    - uses: actions/checkout@v2
    - name: Use Aglio Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install -g aglio
        mkdir build
        aglio -i blueprint.apib --theme-variables flatly -o ./build/index.html
        rsync -av --delete ./data ./build/
        npm cache clean -f
        npm install -g n
        sudo n 12
        npm install -g apib2swagger
        apib2swagger -i blueprint.apib --yaml -o ./build/swagger.yaml
      env:
        CI: true

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
